parameters:
    app.trip_plan.css_file: '%kernel.project_dir%/public/css/trip_plan.css'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Application/Command/'
            - '../src/Domain/Entity/'
            - '../src/Domain/Enum/'
            - '../src/Domain/ValueObject/'
            - '../src/Infrastructure/Exception/'
            - '../src/Kernel.php'

    App\Component\Dompdf\DompdfFactory: ~
    Clegginabox\PDFMerger\PDFMerger: ~
    GuzzleHttp\Client: ~
    Michelf\MarkdownExtra: ~
    Symfony\Component\ExpressionLanguage\ExpressionLanguage: ~
